# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Azavea Open Source Fellowship
email: info@azavea.com
description: >- # this means to ignore newlines until "baseurl:"
  The Azavea Open Source Fellowship Program is a 12-week professional training fellowship that matches software engineering fellows with impactful open source projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: azavea
github_username:  azavea

fellowship_in_session: false # is there a fellowship upcoming or in session
fellowship_timeframe: Summer 2019

collections:
  projects:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post" # automatically sets layout for projects
      is_project: true # automatically set is_post=true for all projects
      published: false # automatically sets all project as drafts
      page_class: "projects"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-avatar

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - deployment
  - Dockerfile
  - Vagrantfile
  - docker-compose.yml
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts
